.goreleaser.yaml, distributions/otelcol/distribution.conf, scripts/generate-goreleaser-config.sh, scripts/goreleaser-templates/docker-manifests.template.yaml
=> Allow customization of properties

.goreleaser.yaml, scripts/goreleaser-templates/docker.template.yaml
=> Use env var for container base image name

distributions/otelcol/manifest.yaml
Updated collector and dependencies to 0.38.0. Note the collector builder was not updated because of its current state of transition into the core repo.
=> Prepare 0.38.0 release

CONTRIBUTING.md, Makefile, distributions/otelcol/manifest.yaml, scripts/build.sh
Closes open-telemetry/opentelemetry-collector#4482
=> Prepare v0.40.0, renames opentelemetry-collector-builder to ocb

distributions/otelcol/otelcol.conf, distributions/otelcol/otelcol.service
Fixes #32
As reported via https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6508, the systemd unit file for the core distribution is currently broken. Turns out, the env file was pointing to non-existing files.
I tested the RPM generated as part of this PR was manually on a fresh Fedora 34 installation.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Fix systemd unit file for otelcol

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, Makefile, configs/otelcol-contrib.yaml, distributions/otelcol-contrib/Dockerfile, distributions/otelcol-contrib/distribution.conf, distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-contrib/otelcol-contrib.conf, distributions/otelcol-contrib/otelcol-contrib.service, distributions/otelcol-contrib/postinstall.sh, distributions/otelcol-contrib/preinstall.sh, distributions/otelcol-contrib/preremove.sh, scripts/build.sh, scripts/goreleaser-templates/builds.template.yaml, scripts/goreleaser-templates/nfpms.template.yaml
=> Add otelcol-contrib release

Makefile, scripts/build.sh
* Add checks for all the tools which are used by the build process.
* Switch from `which` to `commmand` since
** `command` is a builtin to the shell.
** This also fixes an issue which was causing tools to be downloaded
reguardless of whether it has been downloaded previously.
Signed-off-by: Harold Dost <harolddost@gmail.com>
=> Improve the make experience.

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol/manifest.yaml
* Update distributions
** Add references to the core receivers, processors, extensions,
exporters.
* Add flag `include_core` to not use implicit mentions inclusion.
* Minor indentation and spacing edits
Relates to https://github.com/open-telemetry/opentelemetry-collector/issues/3927
Signed-off-by: Harold Dost <harolddost@gmail.com>
=> Explicitly Mention Core Components

distributions/otelcol-contrib/manifest.yaml
Add elasticsearch exporter to the contrib distribution
The elasticsearch exporter has been in contrib for a while though never got included into the cotrib distribution. 
The functionality added by this module has features whom are usable for elasticsearch without the apm module form elastic which is isn't a opensource module. 
As I am unsure why the module hasn't been added in the first place I'm hoping to also get some backstory about why this is.
I intend to add metrics functionality to the exporter since it has support for logs and traces but metrics aren't supported at the moment.
=> Add elasticsearch exporter

distributions/otelcol-contrib/manifest.yaml
postgresqlreceiver is available for few months now and seems to be working fine. There are no open PRs or issues, but it was not enabled for some reason.
I have been using the receiver for few days and everything seem to work fine - collector is stable and PostgreSQL metrics are coming in.
Updates https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6983
=> chore: enable postgresqlreceiver

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, CONTRIBUTING.md, README.md, scripts/goreleaser-templates/docker-manifests.template.yaml, scripts/goreleaser-templates/docker.template.yaml
#39 added support for ARM + ARM64 multi-arch builds, but in #40 a project maintainer reported no longer being able to run goreleaser builds, and reverted it.
ARM(32) builds were removed from goreleaser entirely in #43, so this PR just adds back ARM64 Docker builds. It also updates the GitHub Actions workflows to install support for building the cross-architecture image, and updates the contributing docs with notes about how to set that up on a local system.
=> Build ARM64 Docker images

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7167
=> Add basicauth extension to contrib distribution

.github/workflows/release.yaml, .goreleaser.yaml, goreleaser/configure.go
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
Resolves #49 
The main motivation is to make clear what images are published - the images will be directly linked to this repository. The second motivation is to overcome dockerhub pull limits.
Disclaimer I haven't tested it and I don't have much experience with goreleaser.
=> Publish images to Github container registry (GHCR)

distributions/otelcol-contrib/manifest.yaml
Original receiver implementation: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5320
PR that enabled receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7060
=> Add cloudfoundry receiver to contrib build

.goreleaser.yaml, goreleaser/configure.go
Context: https://github.com/open-telemetry/opentelemetry-collector/issues/5013#issuecomment-1070762107
We remove both Linux and Windows, since the issue affects all OSs.
=> Exclude 386 from opentelemetry-collector-contrib builds

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol/manifest.yaml
**Description**: Remove `replace` directives that are no longer necessary.
They were added by @svrakitin in #62, but can now be removed according to https://github.com/open-telemetry/opentelemetry-collector-releases/pull/62#issuecomment-1019220331
=> [manifests] Remove unnecessary replaces

.github/workflows/ci-goreleaser.yaml, distributions/otelcol/manifest.yaml
This is the second attempt to get this fixed.
Fixes #85
=> Run full build when manifests change

.goreleaser.yaml, goreleaser/configure.go
Darwin 386 build is no longer supported by Go. This is because it dropped support for 32-bit binaries on macOS in [Go 1.15](https://go.dev/doc/go1.15). It makes sense therefore to drop this binary equivalent for the collector also.
Fixes #97 
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
=> Remove Darwin 32-bit release

distributions/otelcol-contrib/manifest.yaml
Requested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9274
cc @jpkrohling
=> Remove deprecated stackdriver exporter

distributions/otelcol-contrib/manifest.yaml
This receiver was not enabled in the contrib distro.
Fix #108
Relates to [PR 9572 in opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9572)
=> [receiver/nginx] enable nginx receiver

distributions/otelcol-contrib/manifest.yaml
This receiver was not enabled in the contrib distro
Fix https://github.com/open-telemetry/opentelemetry-collector-releases/issues/110
=> [receiver/riak] enable riak receiver

distributions/otelcol-contrib/manifest.yaml
This PR adds the transform processor to the contrib distribution.
Tracking transformprocessor alpha release via https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8252
=> [processor/transform] Add transform processor to distribution

.goreleaser.yaml, goreleaser/configure.go
Reverts open-telemetry/opentelemetry-collector-releases#83
=> Revert "Exclude 386 from opentelemetry-collector-contrib builds"

distributions/otelcol-contrib/manifest.yaml
This PR adds the Mezmo exporter to the contrib distribution.
=> [exporter] Add Mezmo exporter to distribution

distributions/otelcol-contrib/manifest.yaml
The fluentbit extension and prometheusexec receiver were marked as deprecated more than 2 months ago. Removing these components from the contrib distribution.
=> [chore] remove deprecated components

distributions/otelcol-contrib/manifest.yaml
Ref https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.54.0/exporter/googlemanagedprometheusexporter
=> Add google managed prometheus exporter to otelcol-contrib

distributions/otelcol-contrib/manifest.yaml
Contrib PR for enabling the sqlquery receiver is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11848
=> add sqlqueryreceiver to contrib manifest

distributions/otelcol-contrib/manifest.yaml
There is a problematic version of `go-connections` that prevents the client from connecting to a docker daemon over HTTP. 
I've raised the issue here: https://github.com/docker/go-connections/issues/99 
And the original PR has discussion around it here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12322#issuecomment-1185029670
cc @mx-psi
=> Replace bad go-connections version

.github/workflows/ci-goreleaser.yaml, .goreleaser.yaml, goreleaser/configure.go
This reverts commit dcaae02a419090a19e97d7d820ec9dd54801b74e to unblock the release.
Related issue: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/170
=> Revert "adding support for linux/ppc64le arch (#156)"

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, CONTRIBUTING.md, goreleaser/configure.go
- re-adding support for linux/ppc64le arch 
- addressing the [issue 170](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/170)
please review and merge.
=> re-adding linux/ppc64le support

.github/workflows/release.yaml
The last 2 releases ([0.58.0](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/2967917951/attempts/1) and [0.59.0](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/2843445596/attempts/1)) have had timeouts that required the build to be re-run.  This PR increases the timeout to 90 minutes to try to prevent this as a short-term solution.
=> [chore] Increase GoReleaser timeout to 90 minutes

distributions/otelcol-contrib/manifest.yaml
Related [#13395](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13395)
=> Add Instana exporter to otel-contrib distributions

distributions/otelcol-contrib/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14106 for context.
=> Add prometheus replace statement for contrib

.github/workflows/ci-goreleaser.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml
=> Upgrade to use go1.19.1, avoids https://nvd.nist.gov/vuln/detail/CVE-2022-27664

distributions/otelcol-contrib/Dockerfile, distributions/otelcol/Dockerfile
- bump alpine base image to 3.16
We might consider using distroless images to reduce the surface attack and have smaller final images.
if this is the desire of the maintainers I can work on that and maybe we can use https://github.com/chainguard-images/static / https://github.com/chainguard-images/alpine-base
=> bump alpine base image to 3.16

.github/workflows/ci-goreleaser.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml
- make sure that it uses the latest patch release available
=> make sure that it uses the latest patch release available

distributions/otelcol-contrib/manifest.yaml
Depends on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13900
=> [manifests] Add headers_setter extension to contrib build.

distributions/otelcol-contrib/manifest.yaml
the remote sampling has been removed from the receiver but its replacement wasn't added to the extensions, cf https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6510
So here it is.
=> Add jaegerremotesampling extension to contrib

distributions/otelcol-contrib/manifest.yaml
Follow up from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14932.
Adds the servicegraph processor to the otel-contrib distribution
=> Add servicegraph procesor to contrib distribution

distributions/otelcol-contrib/README.md, distributions/otelcol/README.md
As the distributions are linked from various places, it makes sense to provide end-users a bit more clarity on what each distro includes.
Fixes #121
=> [docs] add descriptions for distros

distributions/otelcol-contrib/manifest.yaml
This PR adds the awscloudwatch receiver
to the contrib distribution manifest.
Fixes #237
=> Add AWS CloudWatch Receiver

distributions/otelcol-contrib/manifest.yaml
This PR adds the Pure Storage FlashArray receiver to the contrib distribution manifest.
=> Add purefa receiver

.github/workflows/release.yaml
This attempts to split the prepare/release process using the example recommended here: https://goreleaser.com/customization/partial/. This may reduce the amount of time it takes to build the release and hopefully address disk space constraints.
Signed-off-by: Alex Boten <aboten@lightstep.com>
=> [chore] split goreleaser

distributions/otelcol-contrib/manifest.yaml
Introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7840.
=> distributions/otelcol-contrib: add otlpjsonfilereceiver to the manifest

distributions/otelcol-contrib/manifest.yaml
Enables the `datadogprocessor` as part of the contrib distribution, introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16607 and approved in issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15689
Depends on:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16607
* Release of v0.68.0 containing the above.
=> distributions/otelcol-contrib: add datadogprocessor to the manifest

Makefile
This makes e.g. 404 errors much less confusing and would have helped in identifying open-telemetry/opentelemetry-collector/issues/6849 sooner (since otherwise the command passes and you get a plain text file that says `Not Found`)
=> Add --fail option to curl when downloading builder

configs/otelcol-contrib.yaml, configs/otelcol.yaml
Current configuration for docker containers is broken:
```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "logging": 1 error(s) decoding:
* '' has invalid keys: logLevel
2023/02/15 12:00:45 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "logging": 1 error(s) decoding:
* '' has invalid keys: logLevel
```
See: https://github.com/open-telemetry/opentelemetry-collector/commit/bdf63b77e33af2be3bc65e891c379f3a303f6e46
=> fix: move loglevel configuration to verbosity

distributions/otelcol-contrib/manifest.yaml
This component has been unmaintained for over 7 months.
=> [chore] remove unmaintained dotnetdiagnostics receiver

.github/workflows/ci-goreleaser.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml
This bumps the Go version a two patches up to include some security fixes in the standard library.
For more context, please see:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20342
=> Bump Go to 1.19.8 (security fixes in the standard library)

.github/workflows/ci-goreleaser.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml
Bump to Go 1.20 (specifically to `~1.20.3`). This affects only the Go version used in official binaries.
Fixes #286
=> [CI] Bump to Go 1.20

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, Makefile
`--rm-dist` has been deprecated in favor of `--clean`, see https://goreleaser.com/deprecations/#-rm-dist
=> [goreleaser] Switch from deprecated --rm-dist to --clean

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml
This is to address a space limit we've run into w/ caching. Additionally, I changed the workflow to use upload/download artifact to avoid having to create many copies of the cache action for each combination of GOOS+GOARCH.
Linked issue: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/341
I tested the results of upload/download artifact in a private repository.
=> [chore] split goreleaser by GOARCH

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, Makefile
This re-enables the goreleaser split by goarch + goos. As a workaround the fact that the library doesn't support configuring `partial` (https://github.com/orgs/goreleaser/discussions/4033), i've disabled the `ensure-goreleaser-up-to-date` check for now.
=> split builds per goarch

distributions/otelcol-contrib/manifest.yaml
This adds the oracledb receiver, ecs observer, and ecs task observer to the contrib distribution release images.
Fixes #353
=> Add missing components to contrib distribution

distributions/otelcol-contrib/manifest.yaml
After PR #354 and #355 are merged, all of the components currently in contrib will be in the contrib release as a result of this change.
Fixes #46
=> Add all missing components to contrib distribution manifest

distributions/otelcol-contrib/manifest.yaml
Add https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/remoteobserverprocessor to the contrib distribution.
=> Add remoteobserverprocessor to contrib

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, CONTRIBUTING.md, README.md, cmd/goreleaser/internal/configure.go
This pull request is looking to introduce arm32v7 release for otelcol and otel-contrib distribution. 
The pull request builds on top of the changes in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/146, I changed `--platform` to `linux/arm/v7` to hopefully fix the CI build error.
=> Add arm32v7 to release configurations

README.md, distributions/README.md
This PR adds the explicit criteria that a distribution must meet in order to be included in this repository.
Works towards https://github.com/open-telemetry/opentelemetry-collector-releases/issues/360
=> [admin] Add criteria for distributions

distributions/README.md, distributions/otelcol-contrib/README.md
Add rules for which components should be in the Contrib distribution.
Related to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/360
=> [admin] Add contrib component rules

distributions/otelcol-contrib/manifest.yaml
The Datadog Processor is deprecated in favor of the Datadog Connector. This PR adds the connector to the build.
Link to issue: [19740](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19740)
Link to connector: [Datadog Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/datadogconnector)
=> Adding Datadog Connector

distributions/otelcol-contrib/manifest.yaml
resolves issue [392](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/392) by adding the [Webhook Event Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/webhookeventreceiver) to the manifest.yaml in the `otelcol-contrib` distribution
=> added webhook event receiver to manifest

.github/workflows/ci-goreleaser.yaml, .github/workflows/release.yaml, .goreleaser.yaml, cmd/goreleaser/internal/configure.go
The `s390x` CPU architecture is the base for IBM zSeries (aka mainframe) systems. It is beneficial for users of this platform to have a supported way to install pre-compiled binaries for the OpenTelemetry collector in a Linux environment. This issue and associated pull requests will enable the building of all relevant binary artifacts for `linux/s390x` as part of the regular CI pipeline.
IBM has performed tests internally to ensure successful build (via cross-compilation) and runtime (on native platform) integrity of the OpenTelemetry collector (core and contrib) via the unit test suites and specific use-cases.
For more information and discussion please refer to the initial feature request issue (open-telemetry/opentelemetry-collector-releases#378).
=> Add support for linux/s390x architecture

configs/otelcol-contrib.yaml, configs/otelcol.yaml
Explicitly set `0.0.0.0` on the sample configurations so that if we make changes to the defaults Docker users are not affected immediately.
Recommend setting a specific network interface instead of 0.0.0.0 on a comment.
This does not change the behavior since the values set as endpoints are the current defaults.
=> Explicitly set 0.0.0.0 on sample configurations

.github/workflows/ci-goreleaser.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml
This addresses https://pkg.go.dev/vuln/GO-2023-2102
=> [chore] bump go versions

distributions/otelcol-contrib/manifest.yaml
Reverts open-telemetry/opentelemetry-collector-releases#386
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27601.
=> Revert "Replace datadog-agent dependecy versions"

distributions/otelcol-contrib/manifest.yaml
Add [syslog exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/syslogexporter) to contrib distro
Syslog exporter will be available in v0.89 release of opentelemetry-collector-contrib, related pull request: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28902
=> feat: add syslog exporter to contrib distro

distributions/otelcol-contrib/manifest.yaml
The honeycombmarker exporter has entered Alpha stability and is ready to users to try.
=> Add honeycombmarkerexporter to contrib distribution

configs/otelcol-contrib.yaml, configs/otelcol.yaml
This should have been updated some versions ago, the logging exporter is now named debug exporter.
=> update default template with debug exporter

configs/otelcol-contrib.yaml, configs/otelcol.yaml
This should have been added when support for logging was made official.
=> add logs pipeline in the default config

distributions/otelcol-contrib/manifest.yaml
The [namedpipereceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/namedpipereceiver) is currently marked as `Alpha` stability for `logs`, and shows itself as being included in `contrib`. Adding to release for parity.
=> [chore] Add namedpipe receiver

distributions/otelcol-contrib/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31037. datadogprocessor has been deprecated since v0.84.0
=> Remove datadogprocessor

.github/workflows/release.yaml, .goreleaser.yaml, cmd/goreleaser/internal/configure.go
- sign binaries and images with sigstore cosign
also generate sboms for archives and packages
Fixes: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/203
Rehearsal: https://github.com/cpanato/opentelemetry-collector-releases/releases/tag/v99.99.02
checking signed image:
```console
$ COSIGN_EXPERIMENTAL=1 cosign verify ctadeu/opentelemetry-collector-contrib:99.99.02
Verification for index.docker.io/ctadeu/opentelemetry-collector-contrib:99.99.02 --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- Existence of the claims in the transparency log was verified offline
- Any certificates were verified against the Fulcio roots.
[{"critical":{"identity":{"docker-reference":"index.docker.io/ctadeu/opentelemetry-collector- …
```
=> sign binaries and images with sigstore cosign

.goreleaser.yaml, cmd/goreleaser/main.go
Adds a hack to our generator until https://github.com/goreleaser/goreleaser/issues/4635 is addressed
Related to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/429
=> [chore] Ensure partial is generated

.github/workflows/base-release.yaml
The `goreleaser continue` command does not accept `--id` as a parameter.  It should use the result of the previous `release --clean --split --timeout 2h --id ${{ inputs.distribution }}` command which only built/prepped the id we care about.
=> Remove --id from continue command

Makefile, cmd/goreleaser/internal/configure.go, cmd/goreleaser/main.go, scripts/generate-goreleaser.sh
This PR updates the `make generate-goreleaser` command to generate the `.goreleaser.yaml` files in all distributions.
=> [chore] update generate-goreleaser to generate distribution goreleaser files.

distributions/otelcol-contrib/manifest.yaml
Removes spanmetrics processor, relates to open-telemetry/opentelemetry-collector-contrib#29567
=> Remove spanmetrics processor from contrib manifest

distributions/otelcol-contrib/manifest.yaml
The httpforwarder package is deprecated, and the httpforwarderextension is the new package name. No other changes.
=> Use the new package for the httpforwarder extension

distributions/otelcol-contrib/manifest.yaml
The f5 exporter was deprecated 3 weeks ago, removing it now.
=> [chore] remove deprecated component

distributions/otelcol/README.md
Closes https://github.com/open-telemetry/opentelemetry-collector-releases/issues/360
Based on the conversation from the issue I've written out criteria for which components live in core.
=> [chore] Create core distribution component criteria

distributions/otelcol-contrib/manifest.yaml
closes #505 
The OpAMP extension was marked alpha stability recently which means it should be added in here.
=> [chore] Add opampextension

distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
This patch changes the behaviour of how to manage the config file /etc/otelcol-contrib/config.yaml .
It now keeps the existing config file in place and puts the new file as a config.yaml.rpmnew 
```
rpm -vUh otelcol-contrib_0.96.0_linux_amd64.rpm
Verifying... ################################# [100%]
Preparing... ################################# [100%]
Updating / installing...
1:otelcol-contrib-0:0.96.0-1 warning: /etc/otelcol-contrib/config.yaml created as /etc/otelcol-contrib/config.yaml.rpmnew
```
This would fix https://github.com/open-telemetry/opentelemetry-collector-releases/issues/502
=> [rpm/configfile] change behaviour  when upgrading the package 

Makefile, cmd/goreleaser/internal/configure.go
I noticed that the CI workflow wasn't accurately failing when the goreleaser files were out-of-date with the generated code.  Main is actually broken right now.
=> [chore] Fix Makefile

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol/manifest.yaml
Adds the nop components that were released in 0.97.0.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/7316.
=> Add nop components to core and contrib

.github/workflows/base-ci-goreleaser.yaml, .github/workflows/base-release.yaml, .github/workflows/ci.yaml, .github/workflows/shellcheck.yml
- use git hash instead of mutable tags and make sure we install latest go
=> use git hash instead of mutable tags and make sure we install latest go

cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
At `${dayjob}` we currently rely on this OCI label for some automation to determine what level of legal review is required before we're able to use a given image. If one isn't provided, it necessitates some additional red tape. There are definitely ways around it, but I figured the label might be helpful to add for others anyhow.
=> Add `org.opencontainers.image.licenses` label to released images

distributions/otelcol-contrib/manifest.yaml
`zipkinencodingextension` is now alpha. Adding it to the contrib distribution.
=> Add zipkinencodingextension to contrib

distributions/otelcol-contrib/manifest.yaml
Added new component to contrib distro: [Splunk Enterprise Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkenterprisereceiver)
=> Add splunk enterprise receiver to contrib distro

distributions/otelcol-k8s/README.md, distributions/otelcol-k8s/manifest.yaml
=> Add nop exporter to distributions

distributions/otelcol-contrib/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/googleclientauthextension
=> Add googleclientauth extension to release manifest

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-k8s/manifest.yaml, distributions/otelcol/manifest.yaml
#579 did not update modules in the k8s distro. This PR updates them to the latest, and also updates all distros to `v0.103.1` because all distros are released simultaneously.
=> Update k8s distro manifest modules

distributions/otelcol-contrib/manifest.yaml
Part of promotion of this component to alpha, i.e. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33331
=> Add rabbitmq exporter to otelcol-contrib release

distributions/otelcol-contrib/manifest.yaml
This component has gone through the deprecation/unmaintained process in contrib.
=> remove skywalking exporter

distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-k8s/manifest.yaml
Re-do of https://github.com/open-telemetry/opentelemetry-collector-releases/pull/582.
Part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33567.
=> Add otel-arrow components to the contrib and k8s distribution

cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml, go.mod, go.sum
This PR bumps goreleaser in the `go.mod` file to v2 since that is the version that's used in all pipelines anyways (see e.g. [this goreleaser usage](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.github/workflows/base-ci-goreleaser.yaml#L70)).
=> update remaining goreleaser usages to v2

cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
Follow up PR to #244 because the last PR added `/bin/sh` to both the .deb and the .rpm package. But this only works for the RPM package for some reason.
(it also was only requested for the RPM package though)
=> fix linux package dependencies

distributions/otelcol-contrib/manifest.yaml
[[processor/deltatocumulative]](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/deltatocumulativeprocessor) is now alpha (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34747). all major features are implemented, which makes it ready for wider testing.
releasing as part of otelcol-contrib would make that straight forward.
=> contrib: add deltatocumulative

scripts/package-tests/package-tests.sh
This PR removes a workaround first introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31527 which is no longer needed.
Fixes #621
=> [chore] remove package test workaround

.github/workflows/base-ci-goreleaser.yaml
Version 2.3 of goreleaser changed some of the output directory names, making the `Upload linux service packages` task fail silently, causing the `Package tests` tasks to fail at retrieving the package artifacts under test.
This PR pins the version of goreleaser used in the CI to the previous one, v2.2.0, to resolve the issue.
We could also pin to v2.3 and update the expected directory name, but it seems that the name of output directories are not considered stable by goreleaser, so I think a better long-term solution is needed.
=> Pin CI goreleaser version to v2.2.0

distributions/otelcol-contrib/manifest.yaml
This exporter was deprecated 6 months ago, removing it
=> remove deprecated instana exporter

distributions/otelcol-contrib/manifest.yaml
The package `github.com/docker/go-connections` only exists in contrib's generated `go.mod` file in version `v0.5.0`, and does not exist in the replaced version `v0.4.1`. The distro also builds and runs fine without the replace directive.
I believe the [reason](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12322#issuecomment-1185029670) for the replace directive to had been added is out of date. To be sure, I have run the repro scenario described [here](https://github.com/docker/go-connections/issues/99#issuecomment-1782151119) and the behavior with go-connections v0.5.0 was correct - the Docker client tried to connect to the TCP port.
=> [chore] refactor(contrib): remove unused replace directive for `go-connections` package

distributions/otelcol-contrib/Dockerfile, distributions/otelcol/Dockerfile
This PR adds missing HTTP ports to the Dockerfile `EXPOSE` statements for otelcol and otelcol-contrib.
Fixes #692
=> fix: add missing http ports to dockerfile expose statements

distributions/otelcol-k8s/manifest.yaml
Closes https://github.com/open-telemetry/opentelemetry-collector-releases/issues/703
Contrib has gathered some more Alpha components that are generally useful for processing data while running in Kubernetes.  This PR updates the manifest file with new components that meet our [requiremetns](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-k8s#rules-for-component-inclusion).
=> [k8s] Update manifest with new alpha connectors, extensions, processors

distributions/otelcol-contrib/manifest.yaml
Adds the new NTP receiver to the contrib distro. The NTP receiver is separately moving to alpha with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36152
=> Add ntpreceiver to contrib

Makefile, scripts/build.sh
in https://github.com/open-telemetry/opentelemetry-collector/pull/11576 we removed flag `--go` but this script will fail if builder v0.113.0 is used to build and release v0.113.0 distributions.
Pipeline build and release should be sufficient to test this script.
=> remove go flag from distribution build script

renovate.json
This PR takes the renovate config from https://github.com/open-telemetry/opentelemetry-collector (as I found this to be mostly also applicable here, maybe a bit overkill still) and adds a custom regex manager that handles updates of the `version` field for GoReleaser inside the goreleaser-action usages.
Example of an occurrence that this should cover: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/11530fd416496525d0a026be319feb442e0add3b/.github/workflows/base-release.yaml#L83-L88
Hopefully, this works for #668 but renovate config updates are hard to test before merging. The local setup didn't scream, which is a good sign. I will close the issue manually once I'm sure that this PR fixes it and otherwise provide follow-up PRs.
=> Set up default renovate config with regex to handle goreleaser-pro updates

Makefile, cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
Currently, the collector distributions and OCB are not built as position-independent executables.
According to the [OTel Collector Security Audit](https://opentelemetry.io/blog/2024/hardening-the-collector-one/), this could cause potential vulnerabilities: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/618
This PR updates the goreleaser template and the corresponding YAML files to run two separate builds for each distribution that come together for one release each; if the platform and architecture support [Internal Linking in Golang](https://pkg.go.dev/internal/platform#InternalLinkPIESupported), they are built with flag `-buildmode=pie`. If not, they are built the same way as before.
You can see the sample releases in my forked repository: …
=> [chore] build compatible distributions as PIE

.goreleaser.yaml
Sets `release.draft: true`. This would allow us more control over when to announce the release.
=> [chore] Make a draft release instead of directly releasing

cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
This reverts commit 2dbb61e82074e956e4ce2c47f2629972e2e9ed97.
Related to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/783
=> Revert "[chore] build compatible distributions as PIE (#726)"

.github/workflows/base-package-tests.yaml, .github/workflows/package-test.yaml
This PR adds issue creation when the nightly package tests fail. The issue will be created in the -contrib repo with the "release:blocker" label attached.
Fixes https://github.com/open-telemetry/opentelemetry-collector-releases/issues/756
=> [chore] Create issue when nightly tests fail

.github/workflows/scripts/bump-versions.sh, .github/workflows/update-version.yaml
Add quality-of-life enhancement to automate bumping version number in the Makefile as well as the various distribution manifests (as the number of distros grows, this step will become more of a pain).
Feel free to run in your own fork to verify; also see the successful run in my fork: 
https://github.com/jackgopack4/opentelemetry-collector-releases/actions/runs/12320554731/job/34390067049
As well as the generated PR in my fork:
https://github.com/jackgopack4/opentelemetry-collector-releases/pull/23
If this gets merged I will open a PR to update collector release doc in `opentelemetry-collector` repo.
Automatic version bump (increase minor version number) is default behavior; this can be overridden by providing a manual version number update (like bugfix v0.110.0 -> v0.110.1)
=> [chore] add update version automation workflow for artifacts release

.chloggen/add_cgroup_extension.yaml, distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-k8s/manifest.yaml
Adds a new extension to control Go's runtime depending on the environment's cgroup resource limits: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36545
=> add Cgroup runtime extension component

Makefile, scripts/validate-components.sh
Verify that all components declared in manifest.yaml files are defined in the builder-config.yaml from the opentelemetry-collector-contrib repository, ensuring they were built and tested successfully.
Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37087
=> [chore] Add validate-components make target as part of CI

.chloggen/fix_linux_package_scripts.yaml, distributions/otelcol-contrib/postinstall.sh, distributions/otelcol-contrib/preremove.sh, distributions/otelcol-otlp/postinstall.sh, distributions/otelcol-otlp/preremove.sh, distributions/otelcol/postinstall.sh, distributions/otelcol/preremove.sh
=> fix: fix Linux package scripts

README.md
Adds @mowies as a member of releases approvers, after majority approval by the contrib maintainers. 
Moritz is the top contributor to this repository in the past 6 months, and has also contributed in other areas of the Collector. Thanks Moritz for your contributions and congratulations on the promotion!
=> [chore] Add mowies as releases approver

.github/CODEOWNERS
This PR adds the releases-approvers user group as codeowners for all files related to the release.
Parf of https://github.com/open-telemetry/opentelemetry-collector/pull/11577
https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/release-approvers.md
=> [chore] Update codeowners according to releases-approvers RFC

.chloggen/remove_routing_processor.yaml, distributions/otelcol-contrib/manifest.yaml
See motivation with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19739
=> [contrib] remove deprecated routing processor

.chloggen/add_bmchelix_to_otelcol-contrib.yaml, distributions/otelcol-contrib/manifest.yaml
* Updated manifest.yaml
* Added a changelog note
- OpenTelemetry Collector Contrib PR introducing the exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37752)
- OpenTelemetry Collector Contrib Exporter Documentation: [BMC Helix Exporter Documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/bmchelixexporter)
- OpenTelemetry Collector Contrib issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36773
Fixes #822
=> Added BMC Helix exporter to otelcol-contrib releases

.chloggen/add-envoyalsreceiver.yaml, distributions/otelcol-contrib/manifest.yaml
Follows https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38213. Add the receiver to contrib now that it has been promoted to alpha.
=> Add the Envoy ALS receiver to contrib

.github/workflows/base-ci-goreleaser.yaml
This PR fixes the broken nightly package test pipeline by giving the prebuilt collector binary the correct name that is expected in https://github.com/open-telemetry/opentelemetry-collector-releases/blob/20955855e2eb5bcce613a89f22d393b4ec1d250a/distributions/otelcol-contrib/.goreleaser.yaml#L34
My guess is that https://github.com/open-telemetry/opentelemetry-collector-releases/pull/797 changed the path at which the prebuilt collector binary is expected and that was not adapted in the nightly pipelines steps accordingly.
=> [chore] fix nightly package tests

.github/workflows/base-ci-goreleaser.yaml, .github/workflows/base-release.yaml, .github/workflows/builder-release.yaml, .github/workflows/builder-testbuild.yaml, .github/workflows/changelog.yml, .github/workflows/ci-goreleaser-contrib.yaml, .github/workflows/ci-goreleaser-core.yaml, .github/workflows/ci-goreleaser-k8s.yaml, .github/workflows/ci-goreleaser-otlp.yaml, .github/workflows/ci.yaml, cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser-build.yaml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
- removes the build combinations darwin/ppc64le and windows/ppc64le because they are not supported by Go and no artifacts of any sort are generated from them.
- makes pipeline naming more consistent
- Continuous Integration -> CI
- renamed builder pipelines to adhere to same naming scheme as collector distros
Fixes #838
=> [chore] Remove unneeded build combinations and inconsistencies

.github/workflows/base-ci-goreleaser.yaml
Another fix for the package tests. Hopefully, this one sticks.
Failed run that should be fixed by this: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/13667131469
=> [chore] fix package tests

cmd/builder/.goreleaser.yml, cmd/opampsupervisor/.goreleaser.yml
This PR turns of marking OCB releases as latest on github. Nothing needs to be done on the other configs, since the setting is enabled by default, so the usual collector releases should be marked as latest by default.
Fixes #818
=> [chore] only mark collector release as latest

.chloggen/fix_linux_package_scripts.yaml, distributions/otelcol-contrib/postinstall.sh, distributions/otelcol-otlp/postinstall.sh, distributions/otelcol/postinstall.sh
Based on #767. This avoids package manager like `dpkg` to fail in chrooted setups.
=> fix(postinstall): ignore systemctl commands when systemd is not running

cmd/builder/.goreleaser.yml, cmd/opampsupervisor/.goreleaser.yml
This PR fixes the first finding of the GoReleaser check workflow in the collector-core repo.
It removes unneeded build hooks from goreleaser configs that failed when running in the collector-core repo.
After looking into it, I found that they are not actually needed.
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12618
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12619
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/12623
=> [chore] remove unneeded goreleaser hooks

.chloggen/tlscheckreceiver.yaml, distributions/otelcol-contrib/manifest.yaml
This PR adds tlscheckreceiver to OpenTelemetry Collector Contrib
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/tlscheckreceiver
=> Add tlscheckreceiver to otelcol-contrib

scripts/package-tests/package-tests.sh
This should help us identify issues introduced in the release build process related to RPM/deb packaging.
=> [chore] Pull systemd service logs on package test failure

.chloggen/contrib-awscloudwatchmetricsencodingextension.yaml, distributions/otelcol-contrib/manifest.yaml
Add the new awscloudwatchmetricstreams_encoding extension to the contrib distribution.
Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37870
=> Add awscloudwatchmetricstreams encoding to contrib

.github/workflows/update-version.yaml
This PR adapt the update-versions workflow so that users just need to provide, which version should be bumped (minor/patch).
The version calculation is done using off-the-shelve github actions.
Fixes #857
Tested on my fork:
Minor version bump run: https://github.com/mowies/opentelemetry-collector-releases/actions/runs/14034694626/job/39289933536
Path version bump run: https://github.com/mowies/opentelemetry-collector-releases/actions/runs/14034740735/job/39290079279
=> [chore] Calculate next versions automatically

.chloggen/add-loki-exporter.yaml, CHANGELOG.md, distributions/otelcol-contrib/manifest.yaml
The loki exporter was accidentally removed from the collector contrib distro: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/854
Grafana Labs would like to keep it for a while, to support folks who are still in the process of migrating from the loki exporter to otlp exporter
=> add loki exporter to the collector contrib distribution

.chloggen/tyler.remove-dockerhub-destination.yaml, cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, cmd/opampsupervisor/.goreleaser.yml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
Dockerhub has new rate limits that broke our release process.
While others figure out how to increase our rate we're going to stop publishing images to dockerhub.
Related issue: https://github.com/open-telemetry/community/issues/2641
=> Remove dockerhub destination

.chloggen/add-azureblobexporter.yaml, distributions/otelcol-contrib/manifest.yaml
depends on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39303 being merged.
=> feat: add azure blob exporter

cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser-build.yaml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
This will be needed by the eBPF profiler distributions.
=> Add option to allow enabling cgo in distributions

cmd/goreleaser/internal/configure.go
So the eBPF profiler can use custom ld tags, as well as Go tags.
See https://github.com/open-telemetry/opentelemetry-collector-releases/pull/908#discussion_r2041460234
=> Add support for custom ldtags and go tags

CHANGELOG.md
During 0.121.0 release, we modified the container's user group permissions, which broke some current deployments that were relying on those permissions.
Context: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39149#issuecomment-2800986614
=> add breaking change note for 0.121.0 version

.github/workflows/stale.yml
This PR adds the stale action to this repo to take care of old/outdated issues and PRs.
The config was taken from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/close-stale.yaml
=> [chore] add stale action

.chloggen/add-azureauthextension.yaml, distributions/otelcol-contrib/manifest.yaml
Adds azure auth extension to the contrib distribution after stability was [updated to alpha](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39574).
=> Add azureauthextension to contrib distribution

.chloggen/bring-back-docker-builds.yaml, cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, cmd/opampsupervisor/.goreleaser.yml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-ebpf-profiler/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
This reverts commit 0c9c516a935bfd0a7331d36859f924668fb1a34c.
Resolves https://github.com/open-telemetry/community/issues/2641
=> Revert "Remove dockerhub destination (#902)"

renovate.json
So ebpf-profiler is updated weekly with its latest digest.
As discussed in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/933#discussion_r2064828143
=> [chore] Enable ebpf-profiler digest upgrades

.chloggen/add-faro-components.yaml, distributions/otelcol-contrib/manifest.yaml
PR that changes the Stability level of the components to Alpha https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40000
=> [distributions/otelcol-contrib] add faro receiver and faro exporter

.chloggen/tigran_stef.yaml, distributions/otelcol-contrib/manifest.yaml
stefexporter and stefreceiver were recently marked as Alpha and are now ready for limited use and feedback.
=> Add stefexporter and stefreceiver to contrib distribution

.chloggen/release-ebpf-profiler.yaml, .github/workflows/release-ebpf-profiler.yaml
We introduced the eBPF Profiler distribution in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/908.
In order to avoid unforeseen issues, we haven't been publishing the image yet.
This change has been shipped for a few weeks now. So this adds the distribution's release.
=> Release the eBPF Profiler image

.chloggen/add-processor-to-build.yaml, distributions/otelcol-contrib/manifest.yaml
=> Add metricstarttimeprocessor to the contrib distribution

.github/workflows/base-ci-goreleaser.yaml, .github/workflows/base-package-tests.yaml, .github/workflows/base-release.yaml, .github/workflows/builder-release.yaml, .github/workflows/builder-testbuild.yaml, .github/workflows/changelog.yml, .github/workflows/ci-goreleaser-contrib.yaml, .github/workflows/ci-goreleaser-core.yaml, .github/workflows/ci-goreleaser-ebpf-profiler.yaml, .github/workflows/ci-goreleaser-k8s.yaml, .github/workflows/ci-goreleaser-otlp.yaml, .github/workflows/ci.yaml, .github/workflows/fossa.yml, .github/workflows/msi-tests.yaml, .github/workflows/opampsupervisor-release.yaml, .github/workflows/opampsupervisor-testbuild.yaml, .github/workflows/package-test.yaml, .github/workflows/release-contrib.yaml, .github/workflows/release-core.yaml, .github/workflows/release-ebpf-profiler.yaml, .github/workflows/release-k8s.yaml, .github/workflows/release-otlp.yaml, .github/workflows/shellcheck.yml, .github/workflows/stale.yml, .github/workflows/update-version.yaml
Seeing what appear to be permission related failures during the release process (https://github.com/open-telemetry/opentelemetry-collector-releases/issues/965 & #962), rolling this change back to see if it fixes the issues. Reverts open-telemetry/opentelemetry-collector-releases#959
=> Revert "[chore] add default permissions block to workflows"

.chloggen/jackgopack4-datadog-extension.yaml, distributions/otelcol-contrib/manifest.yaml
Depends upon https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40715
Add Datadog Extension to default releases for Contrib distributions.
=> Release Datadog Extension to Contrib

.chloggen/jsok-googlecloudlogentryencodingextension.yaml, distributions/otelcol-contrib/manifest.yaml
Make https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/encoding/googlecloudlogentryencodingextension/README.md available in the contrib distribution.
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37531
=> feat(otelcol-contrib): add googlecloudlogentryencodingextension

.github/workflows/base-release.yaml, .github/workflows/opampsupervisor-release.yaml
We're going away from using a an org-wide token to use project-scoped credentials.
So this switches the Docker token from the global one to a repo-specific one (which has been set already).
See https://github.com/open-telemetry/community/issues/2805
Every distribution should already have access. But please review the mentioned issue to ensure I haven't forgotten anything.
=> [chore] Use DOCKER_TOKEN_COLLECTOR_RELEASES rather than DOCKER_PASSWORD

.github/workflows/regression-tests.yaml
Related to https://github.com/open-telemetry/community/issues/2805
cc @jade-guiton-dd @mowies
=> [chore] verify new docker token

.chloggen/grpcnotrace.yaml, distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-ebpf-profiler/manifest.yaml, distributions/otelcol-k8s/manifest.yaml, distributions/otelcol-otlp/manifest.yaml, distributions/otelcol/manifest.yaml
Removes usages of golang.org/x/net/trace which uses `html/template` and `text/template` in gRPC. These usages disable golang DCE.
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/12747
See https://github.com/grpc/grpc-go/pull/6954
=> Disable net/x/trace usage in gRPC

docs/release.md
Copies over the ['releases' release process](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#producing-the-artifacts-releases-release-manager) into this repository. 
The intent is to remove this from the opentelemetry-collector doc, see open-telemetry/opentelemetry-collector/pull/13464.
=> [chore][docs] Add a release document

renovate.json
This PR removes some old and now faulty renovate config that allowed compatibility with goreleaser-pro versions that were named like `vX.Y.Z-pro` until recently, but are now named normally, e.g. `vX.Y.Z`
=> [chore] remove faulty renovate config for goreleaser-pro

cmd/builder/.goreleaser.yml, cmd/opampsupervisor/.goreleaser.yml
This PR removes the redundant `github:` settings from goreleaser configs of OCB and OpAMP supervisor. Goreleaser will by default always take the current repo.
=> [chore] remove redundant goreleaser settings

.chloggen/remove-loki.yml, distributions/otelcol-contrib/manifest.yaml
Follow up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41413
=> remove loki exporter from contrib distro

cmd/builder/.goreleaser.yml, cmd/opampsupervisor/.goreleaser.yml
#1041 should be reverted because it is blocking the collector snapshot build, as seen in #13493, #13494, and #13296. 
It does not work as expected because we do not trigger releases from opentelemetry-collector-releases; 
instead, releases are triggered in open-telemetry-collector. In that workflow, the release repository is checked out, and only if release.github.name is empty will the current repository’s .git be used.
=> Revert "[chore] remove redundant goreleaser settings (#1041)"

.github/workflows/base-release.yaml
Extracted out of #1016 based on https://github.com/open-telemetry/opentelemetry-collector-releases/pull/1016#discussion_r2230590493
[Tested successfully on my fork](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/16562360126)
=> [chore] use standard GH token for releases

README.md
@mowies has made tremendous amount of contributions to the opentelemetry-collector-releases repo:
PRs reviewed: https://github.com/open-telemetry/opentelemetry-collector-releases/pulls?q=is%3Apr+reviewed-by%3Amowies+
PRs authored: https://github.com/open-telemetry/opentelemetry-collector-releases/pulls?q=is%3Apr+author%3Amowies+
Issues created: https://github.com/open-telemetry/opentelemetry-collector-releases/issues?q=is%3Aissue+author%3Amowies+
Issues commented: https://github.com/open-telemetry/opentelemetry-collector-releases/issues?q=is%3Aissue+commenter%3Amowies+
Commits: https://github.com/open-telemetry/opentelemetry-collector-releases/commits?author=mowies&since=2023-05-31&until=now
We would like to promote @mowies to Maintainer
=> [chore] Promote @mowies to maintainer

.github/workflows/base-release.yaml, .github/workflows/regression-tests.yaml, .github/workflows/release-builder.yaml, .github/workflows/release-opampsupervisor.yaml
This reverts commit 8f30d8c1111ff5a727e3c000955527df21a79cdf.
Fixes #1053 
Re-introduction should be possible now that the new permissions were added to the token. (see [link](https://github.com/open-telemetry/community/issues/2805#issuecomment-3136658536))
=> [chore] re-introduce new dockerhub token

cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, cmd/opampsupervisor/.goreleaser.yml, distributions/otelcol-contrib/.goreleaser-build.yaml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
Fixes #1065 
The nightly release failed because of a mismatch between nightly versions that goreleaser used during the 2 step release in base-release.yml
It used both 202507311344 and 202507311345 as timestamps since the nightlies::version_template is set to include a timestamp. This is changed here, and now we use the commit hash instead since that is deterministic, unlike the timestamp.
=> [chore] use commit sha instead of timestamp for nightly releases

.chloggen/prometheus-exporter.yaml, distributions/otelcol-contrib/manifest.yaml, distributions/otelcol-ebpf-profiler/manifest.yaml, distributions/otelcol-k8s/manifest.yaml, distributions/otelcol-otlp/manifest.yaml, distributions/otelcol/manifest.yaml
Context: https://github.com/open-telemetry/opentelemetry-collector/pull/13466
go.opentelemetry.io/otel/exporters/prometheus v0.59.x has a bug leading to unexpected suffix in metric names, we want to stay with v0.58.0 in the artifacts.
=> Pins go.opentelemetry.io/otel/exporters/prometheus to v0.58.0

Makefile
OCB does not have `0.131.1` , should still be on `0.131.0`
=> [chore] fix OCB version

.github/workflows/ci.yaml
this PR optimizes pipelines a little bit by making the CI pipelines more parallelized
TODO:
- remove the "Build" job from required jobs for merges
- merge this PR
- add the "build-result" job instead to the required jobs for merges
=> [chore] make CI more parallel

.chloggen/rv64.yaml, .github/workflows/base-ci-goreleaser.yaml, .github/workflows/base-release.yaml, .github/workflows/ci-builder.yaml, .github/workflows/ci-goreleaser-contrib.yaml, .github/workflows/ci-goreleaser-core.yaml, .github/workflows/ci-goreleaser-k8s.yaml, .github/workflows/ci-goreleaser-otlp.yaml, .github/workflows/ci-opampsupervisor.yaml, .github/workflows/release-builder.yaml, .github/workflows/release-contrib.yaml, .github/workflows/release-core.yaml, .github/workflows/release-opampsupervisor.yaml, .github/workflows/release-otlp.yaml, CONTRIBUTING.md, cmd/builder/.goreleaser.yml, cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser-build.yaml, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
New Tier 3 platform: `riscv64` architecture is now included, allowing the collector to be built and distributed for this platform.
Fixes #968
=> Add riscv64 arch

.chloggen/mowies-fix-checksums.yaml, cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-ebpf-profiler/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
=> Fix checksum files being overwritten by windows release

.github/workflows/base-ci-binary.yaml, .github/workflows/ci.yaml
This renames the 2 workflows that currently have the same name to make it easier to distinguish them.
=> [chore] rename workflows

.github/workflows/base-release.yaml
=> [chore] move computing the git tag into a separate Linux-only step

.chloggen/main.yaml, distributions/otelcol-contrib/manifest.yaml
Promoting `isolationforestprocessor` near realtime anomaly detection processor to **alpha**
Adding the initial implementation of the `isolationforestprocessor` for OpenTelemetry Collector.  
This feature introduces anomaly detection using the Online Isolation Forest algorithm applied to streaming - traces, metrics, and logs. The processor evaluates each incoming signal and tags it with an `anomaly_score` and `anomaly_is_anomaly` attribute based on a configurable threshold and contamination rate using a moving time window enabling us to perform anomaly detection in near-realtime instead of performing the same as an async analysis increasing the MTTD.
This lays the foundation for unsupervised anomaly detection in observability pipelines.
[New component: Isolation-Forest anomaly detection …
=> isolationforestprocessor - alpha release

cmd/goreleaser/internal/configure.go, distributions/otelcol-contrib/.goreleaser.yaml, distributions/otelcol-ebpf-profiler/.goreleaser.yaml, distributions/otelcol-k8s/.goreleaser.yaml, distributions/otelcol-otlp/.goreleaser.yaml, distributions/otelcol/.goreleaser.yaml
This PR updates some deprecated fields in the goreleaser configs.
See [link](https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/17128206347/job/48585077753#step:16:34) for the deprecation warnings.
=> [chore] update deprecated goreleaser fields

.github/workflows/base-ci-binary.yaml
It looks like it's just testing the release workflow (but not doing the release)? so I think it doesn't need any special token permissions(?)
Resolves
- https://github.com/open-telemetry/opentelemetry-collector-releases/security/code-scanning/69
=> [chore] Add explicit token permission

.github/workflows/scripts/bump-versions.sh, .github/workflows/update-version.yaml
This PR fixes an issue during release where the manifest version of distros was updated to one version to far.
Since the component versions are now bumped by renovate, the bump-versions script doesn't need to be concerned with them anymore and therefore needs to do less things in general.
Fixes #1186
=> chore: fix bump-versions
