- opentelemetry-collector/manifest.yaml
> Update to core v0.34.0

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> Use Go 1.17

- Makefile
- distributions/otelcol/manifest.yaml
> Use git tags for 0.34.0 release

- .goreleaser.yaml
- scripts/goreleaser-templates/builds.template.yaml
> Remove windows-arm64 from the build matrix

- .github/workflows/release.yaml
- .goreleaser.yaml
- scripts/goreleaser-templates/docker-manifests.template.yaml
- scripts/goreleaser-templates/docker.template.yaml
> Publish images to opentelemetry namespaces

- Makefile
- distributions/otelcol/manifest.yaml
Closes #16
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Release v0.35.0

- README.md
> Fix otelcol name

- Makefile
- distributions/otelcol/manifest.yaml
> Release otelcol v0.36.0

- .goreleaser.yaml
- scripts/goreleaser-templates/docker-manifests.template.yaml
- scripts/goreleaser-templates/docker.template.yaml
> Remove 'v' from the container image version

- Makefile
- distributions/otelcol/manifest.yaml
Closes open-telemetry/opentelemetry-collector#4528
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Prepare v0.41.0

- distributions/otelcol-contrib/manifest.yaml
Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7951
> Add k8s_events receiver to contrib build

- distributions/otelcol-contrib/manifest.yaml
Follow the advice: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6907#discussion_r803509769
> Add clickhouse exporter

- distributions/otelcol-contrib/otelcol-contrib.service
- distributions/otelcol/otelcol.service
> Fix path to the distribution binaries in packages

- distributions/otelcol-contrib/manifest.yaml
Follows [(contrib)#9678](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9678)
Resolves #117 
Resolves #116 
Resolves #115 
Resolves #114
> Add couchdb, elasticsearch, mongodb, and rabbitmq receivers

- .github/dependabot.yml
> Setup dependabot updates for the release repo

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> Typo: replace set up with setup

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/release.yaml
> Upgrade all docker/actions to v2

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/release.yaml
> Remove unnecessary id from github action steps

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> Run build and release with golang 1.18

- distributions/otelcol-contrib/manifest.yaml
This PR is in response to: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10847#issuecomment-1150556736
> add expvar receiver to contrib distribution

- .github/workflows/ci-goreleaser.yaml
- .goreleaser.yaml
- goreleaser/configure.go
> adding support for linux/pp64le arch

- distributions/otelcol-contrib/manifest.yaml
Receiver:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/nsxtreceiver
Resolves: #215
Resolves: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14788
> Add NSX-T Receiver to contrib

- .goreleaser.yaml
- cmd/goreleaser/main.go
- go.mod
- go.sum
> Upgrade to yaml.v3

- .goreleaser.yaml
- cmd/goreleaser/internal/configure.go
Fix https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73
> Update goreleaser to add latest tags

- distributions/otelcol-contrib/manifest.yaml
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11559
FYI @djaglowski
> Added Solace Receiver to otelcol-contrib manifest

- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol/manifest.yaml
> [chore] prepare 0.64.1

- Makefile
> Merge add-tag and push-tags to simplify release and make it consistent with core and contrib

- Makefile
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
> Fix default remote for push-tags target

- .github/workflows/shellcheck.yml
- scripts/build.sh
This fixes issues detected by shellcheck and adds shellcheck GitHub Actions workflow.
Fixes #264
> Add shellcheck workflow

- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol/manifest.yaml
- Adds `forward` connector to core and contrib ditros
- Adds `count` connector to contrib distro
> Add connectors to distributions

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
To address https://pkg.go.dev/vuln/GO-2023-1840
> [chore] bump go version

- distributions/otelcol-contrib/manifest.yaml
> Add haproxyreceiver to the contrib distribution

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Bump to Go 1.21
Fixes https://github.com/open-telemetry/opentelemetry-collector-releases/issues/383
> [CI] Bump to Go 1.21

- distributions/otelcol-contrib/manifest.yaml
Follow up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26694
> add routing connector to contrib release

- distributions/otelcol-contrib/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27284
> Remove Parquet Exporter from contrib distro

- .github/workflows/ci-goreleaser.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
No security fixes on this one, but good to have
> [chore] Explictly bump to go1.21.7

- distributions/otelcol-contrib/manifest.yaml
Follows https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31051
> Remove unfinished file receiver

- .github/workflows/base-release.yaml
saw the error in https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/7991621055
> fix paramenter

- distributions/otelcol-contrib/manifest.yaml
Follows https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31040
> Update storage modules

- .github/workflows/base-release.yaml
> [fix] Use ** in upload-artifact path

- .github/workflows/base-release.yaml
> [fix] dist is now inside each 'distribution'

- .github/workflows/base-release.yaml
> [fix] further fixes to upload/download artifacts

- distributions/otelcol-contrib/Dockerfile
- distributions/otelcol/Dockerfile
Should there be a dependabot alert for this? I would be happy to contribute that as well.
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>
> [chore] bump alpine version to 3.19

- distributions/otelcol-contrib/manifest.yaml
Adding connector as indicated here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31820/files#r1543630058
> Add exceptionsconnector

- distributions/otelcol-contrib/manifest.yaml
Add new component: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31647
> add grafanacloud connector to contrib release

- distributions/otelcol-contrib/manifest.yaml
Add new compponent: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26376
> add ackextension to contrib release

- .github/workflows/base-ci-goreleaser.yaml
- .github/workflows/base-release.yaml
This PR fixes some pipeline `if` conditionals that didn't work correctly.
> fix some broken conditionals in pipelines

- cmd/goreleaser/internal/configure.go
- distributions/otelcol-contrib/.goreleaser.yaml
- distributions/otelcol/.goreleaser.yaml
Fixes #244 
This re-does the PR already prepared but then closed here: #245
> Add /bin/sh dependency to linux packages

- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol-k8s/manifest.yaml
Moved suggestions to PR to address branch protection issues
> add logdedup processor

- distributions/otelcol-contrib/manifest.yaml
Follow up PR to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34788
> add geoip processor to contrib

- distributions/otelcol-contrib/manifest.yaml
Reverts https://github.com/open-telemetry/opentelemetry-collector-releases/pull/686
> Revert removal of googlecloudspanner receiver

- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol-k8s/manifest.yaml
- distributions/otelcol-otlp/manifest.yaml
- distributions/otelcol/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector/pull/11588
> Remove otel-version usage, removed from builder

- renovate.json
This PR adapts the regex manager for renovate to make the regex less greedy.
Hopefully solves #668
> [chore] fix renovate regex config

- .github/workflows/builder-testbuild.yaml
- .github/workflows/ci-goreleaser-contrib.yaml
- .github/workflows/ci-goreleaser-core.yaml
- .github/workflows/ci-goreleaser-k8s.yaml
- .github/workflows/ci-goreleaser-otlp.yaml
- .github/workflows/ci.yaml
- .github/workflows/shellcheck.yml
Fixes #750 
Depends on https://github.com/open-telemetry/community/issues/2457
> chore: Add workflows to merge group

- .chloggen/add_libhoneyreceiver.yaml
- distributions/otelcol-contrib/manifest.yaml
Related issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36693
> [contrib] Add Libhoney receiver

- README.md
Lists approvers and maintainers after open-telemetry/opentelemetry-collector/pull/11577
> [chore] Add list of approvers and maintainers

- .chloggen/add_interval_processor.yaml
- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol-k8s/manifest.yaml
Solves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37501
> Update contrib and k8s distributions to match main repo

- .chloggen/add-aesprovider.yaml
- distributions/otelcol-contrib/manifest.yaml
Follow-up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38252.
> Add the AES provider to contrib

- .chloggen/add-secretsmanagerprovider.yaml
- distributions/otelcol-contrib/manifest.yaml
Follow-up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38251.
> Add the Secrets Manager Provider to contrib

- .chloggen/remove_lokiexporter.yaml
- distributions/otelcol-contrib/manifest.yaml
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38374
> [contrib] remove lokiexporter

- .github/workflows/scripts/bump-versions.sh
- .github/workflows/update-version.yaml
The option names were a bit confusing to me during the v0.120.0 release, here is a suggestion on how to clarify them
> [chore] Update automated workflow to make it clearer

- .github/workflows/base-release.yaml
- .github/workflows/builder-release.yaml
Unclear if this is used anywhere, removing based on https://github.com/open-telemetry/opentelemetry-collector-releases/pull/858#discussion_r1983612398
> [chore] clean up short_sha

- .chloggen/add-tcpcheckreceiver.yaml
- distributions/otelcol-contrib/manifest.yaml
Follow-up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38443.
> Add tcpcheckreceiver To Contrib

- Makefile
- distributions/otelcol-contrib/manifest.yaml
- distributions/otelcol-k8s/manifest.yaml
- distributions/otelcol-otlp/manifest.yaml
- distributions/otelcol/manifest.yaml
This includes the patch to address a regression in configuration parsing.
> [chore] prepare v0.122.1 release

- .chloggen/dinesh.gurumurthy_add-schema-processor-to-contrib.yaml
- distributions/otelcol-contrib/manifest.yaml
The pr adds schema processor to the collector contrib.
> Add schema processor to the collector conrib

- .chloggen/feat_add-kafkatopicsobserver.yaml
- distributions/otelcol-contrib/manifest.yaml
See [https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37665](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37665)
> feat: add kafkatopicsobserver extension

- .github/workflows/base-ci-goreleaser.yaml
> chore: add config_file and (otelcol|docker) run options to base ci goreleaser

- renovate.json
This follows other repos in the org to improve renovatebot's ability to help w/ updating github workflows.
> [chore] update renovatebot config

- .github/workflows/base-ci-goreleaser.yaml
- .github/workflows/base-package-tests.yaml
- .github/workflows/base-release.yaml
- .github/workflows/builder-release.yaml
- .github/workflows/builder-testbuild.yaml
- .github/workflows/changelog.yml
- .github/workflows/ci-goreleaser-contrib.yaml
- .github/workflows/ci-goreleaser-core.yaml
- .github/workflows/ci-goreleaser-ebpf-profiler.yaml
- .github/workflows/ci-goreleaser-k8s.yaml
- .github/workflows/ci-goreleaser-otlp.yaml
- .github/workflows/ci.yaml
- .github/workflows/fossa.yml
- .github/workflows/msi-tests.yaml
- .github/workflows/opampsupervisor-release.yaml
- .github/workflows/opampsupervisor-testbuild.yaml
- .github/workflows/package-test.yaml
- .github/workflows/release-contrib.yaml
- .github/workflows/release-core.yaml
- .github/workflows/release-ebpf-profiler.yaml
- .github/workflows/release-k8s.yaml
- .github/workflows/release-otlp.yaml
- .github/workflows/shellcheck.yml
- .github/workflows/stale.yml
- .github/workflows/update-version.yaml
This addresses a few of the dependabot warnings for the repo.
> [chore] add default permissions block to workflows

- .github/workflows/regression-tests.yaml
This PR adds a regression test workflow which i imagine to be used for future issues like the recent [docker token issue](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/995). For now, i just added a test for that but the workflow can grow with new bugs in the future.
> [chore] add regression test workflow

- .github/workflows/base-release.yaml
- .github/workflows/regression-tests.yaml
- .github/workflows/release-builder.yaml
- .github/workflows/release-opampsupervisor.yaml
This cherry picks #982 and includes the fix mentioned in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/1004#discussion_r2190317832
Fixes #997
> [chore] Re-enable new dockerhub tokens

- .github/workflows/base-release.yaml
- .github/workflows/regression-tests.yaml
- .github/workflows/release-builder.yaml
- .github/workflows/release-opampsupervisor.yaml
This reverts commit dd11b5b2be22dd3ee275959e4f4eeb4a690ee602.
> Revert "[chore] Re-enable new dockerhub tokens (#1031)"

- .chloggen/add_skywalkingencodingextension_in_otel_col_contrib.yaml
- distributions/otelcol-contrib/manifest.yaml
fix  https://github.com/open-telemetry/opentelemetry-collector-releases/issues/1078
fix https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/41717
> add skywalkingencodingextension

- cmd/goreleaser/internal/configure.go
- distributions/otelcol-contrib/.goreleaser.yaml
- distributions/otelcol-ebpf-profiler/.goreleaser.yaml
- distributions/otelcol-k8s/.goreleaser.yaml
- distributions/otelcol-otlp/.goreleaser.yaml
- distributions/otelcol/.goreleaser.yaml
> fix: Correctly check for windows OS in goreleaser config

- .github/workflows/base-binary-release.yaml
> [chore] fix wrong tag in binary release pipeline

- .github/workflows/base-binary-release.yaml
- .github/workflows/release-ebpf-profiler.yaml
It likes top-level permission blocks.
Resolves
- https://github.com/open-telemetry/opentelemetry-collector-releases/security/code-scanning/64
- https://github.com/open-telemetry/opentelemetry-collector-releases/security/code-scanning/72
> [chore] Make scorecard happy
